# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dgarcia-language-bot-c862

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Compress files
        run: |
          zip -r deploy.zip . -x node_modules/**\*

      - name: 'Deploy to Azure Web App'
        uses: azure/webapp-deploy@v1
        with:
          app-name: 'dgarcia-language-bot-c862'
          slot-name: 'Production'
          package: deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EBB468DDCBE74D3FA8005836A7CD555B }}
          
